### ISSUE TITLE
Allow Hugo files to go through the Parchment proxy?

### ISSUE THREAD

**Issue by curiousdannii** [juhana/hugojs#1]
Just a thought, rather than having your own CORS proxy (and requiring those who want to host their own terp to need a PHP capable server) it would be very easy for me to allow Hugo files to go through the Parchment proxy. Is this something you'd be interested in?

**Comment by juhana** [comment]
That would be optimal, thank you! In the future the proxy would need to allow Hugo resource files too, if that's possible.

**Comment by curiousdannii** [comment]
I've removed all the filtering now (but there is a 32MB limit.)

https://proxy.iplayif.com/
https://proxy.iplayif.com/proxy/?url=http://www.joltcountry.com/downloads/HugoComp/clock.hex
https://proxy.iplayif.com/proxy/?url=http://www.joltcountry.com/downloads/HugoComp/clock.hex&encode=base64
https://proxy.iplayif.com/proxy/?url=http://www.joltcountry.com/downloads/HugoComp/clock.hex&encode=base64&callback=hugojs
