### ISSUE TITLE
ASYNCIFY will be going away

### ISSUE THREAD

**Issue by curiousdannii** [juhana/hugojs#2]
Just a heads up that [ASYNCIFY will be going away](https://github.com/kripken/emscripten/pull/5801).

You'll have to either keep to an older version of emscripten or change to EmterpreterAsync.

**Comment by juhana** [comment]
Thanks – I've been meaning to update because the latest Emscripten has already not been able to compile the project for a while.

**Comment by curiousdannii** [comment]
The removal has been indefinitely postponed.
